[package]
name = "ruid"
version = "0.1.0"
edition = "2024"

[dependencies]
fontdue = "0.9.3"
pixels = "0.15.0"
rand = { version = "0.9.1", features = ["simd_support"] }
rayon = "1.10.0"
winit = "0.30.9"
